### ISSUE TITLE
ubuntu install of tensorflow notes

### ISSUE THREAD

**Issue by lgbouma** [ASvyatkovskiy/PythonWorkshop#1]
This link https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#pip-installation gives the binary urls for different python versions (e.g., 2.7 I think was the default link given in the installation README).

Alternatively, once `source activate PythonWorkshop` has been run and you're in the environment, I just did `conda install -c conda-forge tensorflow` and it worked.

**Comment by ASvyatkovskiy** [comment]
Good to know - I will look to update the instructions accordingly.
